spring:
  profiles:
    active: local

  datasource:
    url: jdbc:h2:mem:database

  h2:
    console:
      enabled: true

custom:
  security:
    password-encode:
      iteration-count: 65536
      key-length: 256
